chore: add introduction
veramolabs/did-eth pull request #30
Opened 2023-02-23 18:52 UTC by nickreynolds

2023-03-09 17:08 UTC, otto-mora approved these changes

2023-03-10 10:22 UTC, mirceanis requested changes
Looks good.
I'd remove the "DID document" mention for on-chain resolution

2023-03-10 10:22 UTC, mirceanis commented on did-eth-method-draft.md
> +`did-eth` is intended to be a modern DID method for the Ethereum ecosystem. It serves as a successor to `did-ethr` in this regard, and should be fully [DID-core](https://www.w3.org/TR/did-core/) comp
I believe that on-chain resolution should not be in the form of a DID document.

```suggestion
`did-eth` is intended to be a modern DID method for the Ethereum ecosystem. It serves as a successor to `did-ethr` in this regard, and should be fully [DID-core](https://www.w3.org/TR/did-core/) compliant, fully supporting all possible verification methods and services. This DID method should be resolvable both off-chain (by querying for and processing EVM events) as well as on-chain (by processing EVM state directly from within a smart contract), although it should be considered acceptable if the on-chain resolution involves only a subset of verification methods or services, as specified later in this document.
```

2023-03-16 16:15 UTC, mirceanis approved these changes

2023-03-16 16:19 UTC, merged